swagger: '2.0'
info:
  title: BedOff
  description: 'Bulk Hotel Booking Order from client'
  contact:
    email: nafis.mohammad65@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
host: bedoff.swagger.io
tags:
  - name: booking
    description: ''
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: order
    description: Access toBedsOffApi
  - name: user
    description: Operations about user
  - name: hotel
    description: Operations about hotel
  - name: guest
    description: Operations about guest
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
schemes:
  - http
paths:
  /OrderUpload:
    post:
      tags:
        - order
      summary: Add a Booking Order(Upload a Excel sheet)
      consumes:
         - multipart/form-data
      parameters:
         - in: formData
           name: upfile
           type: file
           description: The file to upload.
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/BookingResults'
        '405':
          description: Invalid input
      x-codegen-request-body-name: body
  /BookingsByIds/:
    get:
      tags:
        - booking
      summary: Find booking by ID
      description: Returns a single booking
      operationId: getBookingsList
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            items:
              $ref: '#/definitions/Booking'
        '400':
          description: ''
        '404':
          description: booking not found
    delete:
      tags:
        - booking
      summary: Delete a booking
      operationId: deleteBookingLists
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
      responses:
        '400':
          description: ''
        '404':
          description: ''
  /Booking/:
    post:
      tags:
        - booking
      summary: save a new booking
      consumes:
        - application/json
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Booking'
      responses:
        '405':
          description: Invalid input

      x-codegen-request-body-name: body
    patch:
      tags:
        - booking
      summary: patch a booking
      consumes:
        - application/json
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Booking'
      responses:
        '405':
          description: Invalid input

      x-codegen-request-body-name: body

  /Bookings/:
    post:
      tags:
        - booking
      summary: get Bookings for provided Filters
      consumes:
        - application/json
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/BookingFilter'
      responses:
        '405':
          description: Invalid input

      x-codegen-request-body-name: body
  /guestsByIds/:
    post:
      tags:
        - guest
      summary: Creates list of users with given input array
      operationId: createUsersWithListInput
      consumes:
        - application/json
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
              
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            items:
              $ref: '#/definitions/Guest'
  /user/{id}:
    get:
      tags:
        - user
      summary: Find booking by ID
      description: Returns a single user
      operationId: getUser
      parameters:
        - name: id
          in: path
          description: ID of user to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            items:
              $ref: '#/definitions/User'
        '400':
          description: ''
        '404':
          description: booking not found
  /user:
    post:
      tags:
        - user
      summary: create user
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
      responses:
        '405':
          description: Invalid input
  /Hotel/:
    post:
      tags:
        - hotel
      summary: get hotels by filter
      consumes:
        - application/json
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/HotelFilter'
      responses:
        '405':
          description: Invalid input

      x-codegen-request-body-name: body
    patch:
      tags:
        - hotel
      summary: patch a hotel
      consumes:
        - application/json
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Hotel'
      responses:
        '405':
          description: Invalid input

      x-codegen-request-body-name: body
definitions:
  BookingResults:
      type: object
      properties:
        Bookings:
          type: array
          items:
            $ref: '#/definitions/Guest'
        ResponseMessage:
          type: string
      xml:
        name: BookingResults
  BookingFilter:
      type: object
      properties:
        Status:
          type : integer
          format: int64
        HotelKey:
          type : integer
          format : int64
        CheckInDate:
          type : integer
          format : int64
        CheckoutDate:
          type : integer
          format : int64
        GuestName:
          type : string
      xml:
        name: BookingFiter
  BookingOrderReq:
    type: object
    properties:
      BookingGroup:
        $ref: '#/definitions/BookingGroup'
    xml:
      name: BookingOrderReq
  BookingOrder:
    type: object
    properties:
      id:
        type: integer
        format: int64
    xml:
      name: BookingOrder
  BookingGroup:
    type: object
    properties:
      id:
        type: integer
        format: int64
      CheckIn:
        type: string
        format: date-time
      BookingOrder:
        $ref: '#/definitions/BookingOrder'
      CheckOut:
        type: string
        format: date-time
      status:
        type: string
        description: Order Status
        enum:
          - placed
          - approved
          - delivered
      complete:
        type: boolean
        default: false
    xml:
      name: BookingGroup
  Booking:
    type: object
    properties:
      id:
        type: integer
        format: int64
      EmpId:
        type: integer
        format: int64
      BookingGroup:
        $ref: '#/definitions/BookingGroup'
      CheckIn:
        type: string
        format: date-time
      CheckOut:
        type: string
        format: date-time
      status:
        type: string
        description: Order Status
        enum:
          - placed
          - approved
          - delivered
      complete:
        type: boolean
        default: false
    xml:
      name: Booking
  Hotel:
    type: object
    properties:
      id:
        type: integer
        format: int64
      hotelname:
        type: string
      Address:
        $ref: '#/definitions/Address'
      email:
        type: string
      phone:
        type: string
      account:
        $ref: '#/definitions/Account'
    xml:
      name: Hotel
  HotelFilter:
    type: object
    properties:
      Active:
        type : integer
        format: int64
      State:
        type : string
      Name:
        type : string
  Account:
    type: object
    properties:
      id:
        type: integer
        format: int64
      accountName:
        type: string
      IFSC:
        type: string
    xml:
      name: Account
  Guest:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      Address:
        $ref: '#/definitions/Address'
      email:
        type: string
      phone:
        type: string
    xml:
      name: Guest
  Address:
    type: object
    properties:
      id:
        type: integer
        format: int64
      AddressLine1:
        type: string
      AddressLine2:
        type: string
      ZipCode:
        type: integer
        format: int64
    xml:
      name: Address
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      Role:
        type: string
    xml:
      name: Address




